name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use GitHub Token
        env:
          TOKEN: ${{ secrets.GToken }}
        run: echo "Your token is stored securely"
